"""fix typo

Revision ID: 3faf069aae10
Revises: c108100ad5f8
Create Date: 2026-03-13 13:20:01.760354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3faf069aae10'
down_revision: Union[str, None] = 'c108100ad5f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('strava_token_expires_at', sa.Integer(), nullable=True))
    op.drop_column('users', 'stava_token_expires_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('stava_token_expires_at', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('users', 'strava_token_expires_at')
    # ### end Alembic commands ###
