"""add strava token fields and fix typos

Revision ID: 72fc10b3a79b
Revises: 
Create Date: 2026-03-13 12:39:01.516703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72fc10b3a79b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('strava_athlete_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('stava_token_expires_at', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('prefered_pace_min_km', sa.Float(), nullable=True))
    op.drop_constraint('users_strava_athelete_id_key', 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['strava_athlete_id'])
    op.drop_column('users', 'strava_athelete_id')
    op.drop_column('users', 'preffered_pace_min_km')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('preffered_pace_min_km', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('strava_athelete_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint('users_strava_athelete_id_key', 'users', ['strava_athelete_id'])
    op.drop_column('users', 'prefered_pace_min_km')
    op.drop_column('users', 'stava_token_expires_at')
    op.drop_column('users', 'strava_athlete_id')
    # ### end Alembic commands ###
