"""fix typo

Revision ID: c108100ad5f8
Revises: 72fc10b3a79b
Create Date: 2026-03-13 12:41:12.277507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c108100ad5f8'
down_revision: Union[str, None] = '72fc10b3a79b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('preferred_pace_min_km', sa.Float(), nullable=True))
    op.drop_column('users', 'prefered_pace_min_km')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('prefered_pace_min_km', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('users', 'preferred_pace_min_km')
    # ### end Alembic commands ###
